# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1.xci
# IP: The module: 'Genesys_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1.xci
# IP: The module: 'Genesys_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/newGenesysDDR/Genesys.srcs/sources_1/bd/Genesys/ip/Genesys_clk_wiz_0_1/Genesys_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Genesys_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
