webtalk_init -webtalk_dir D:/Program-Files/Vivado/Vivado/vivado_prj/DAC_BUFFER_CLK/DAC_BUFFER_CLK.sim/sim_1/behav/xsim/xsim.dir/Buffer_clk_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 28 17:36:32 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212231338_0_0_729" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5b32bc22-4f0f-4373-9252-cfdb65a577aa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fb96fc3633324781be6252b7d762f015" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "48" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "278469500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.53_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14868_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1407855679 -regid "212231338_0_0_729" -xml D:/Program-Files/Vivado/Vivado/vivado_prj/DAC_BUFFER_CLK/DAC_BUFFER_CLK.sim/sim_1/behav/xsim/xsim.dir/Buffer_clk_test_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Program-Files/Vivado/Vivado/vivado_prj/DAC_BUFFER_CLK/DAC_BUFFER_CLK.sim/sim_1/behav/xsim/xsim.dir/Buffer_clk_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Program-Files/Vivado/Vivado/vivado_prj/DAC_BUFFER_CLK/DAC_BUFFER_CLK.sim/sim_1/behav/xsim/xsim.dir/Buffer_clk_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
