
set_property IOSTANDARD LVCMOS33 [get_ports pingpong_clk_0]


set_property IOSTANDARD LVCMOS33 [get_ports pingpong_clk_1]
set_property PACKAGE_PIN V27 [get_ports pingpong_clk_0]

set_property IOSTANDARD LVCMOS33 [get_ports {led_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[0]}]
set_property PACKAGE_PIN W23 [get_ports {led_0[7]}]
set_property PACKAGE_PIN W24 [get_ports {led_0[6]}]
set_property PACKAGE_PIN V26 [get_ports {led_0[5]}]
set_property PACKAGE_PIN V20 [get_ports {led_0[4]}]
set_property PACKAGE_PIN U29 [get_ports {led_0[3]}]
set_property PACKAGE_PIN U30 [get_ports {led_0[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_0[1]}]
set_property PACKAGE_PIN T28 [get_ports {led_0[0]}]
set_property PACKAGE_PIN V27 [get_ports pingpong_clk_1]

set_property PACKAGE_PIN G19 [get_ports rst_0]

set_property IOSTANDARD LVCMOS33 [get_ports rst_0]

set_property PACKAGE_PIN AC26 [get_ports data_out_0]
set_property PACKAGE_PIN H24 [get_ports load_0]
set_property PACKAGE_PIN G25 [get_ports rst_1]
set_property IOSTANDARD LVCMOS33 [get_ports data_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports load_0]
set_property IOSTANDARD LVCMOS33 [get_ports rst_1]
set_property IOSTANDARD LVCMOS33 [get_ports sync_0]
set_property PACKAGE_PIN W22 [get_ports clk_dac_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_dac_0]

set_property PACKAGE_PIN V24 [get_ports dac_sync_0]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sync_0]

set_property PACKAGE_PIN V24 [get_ports dac_sync_1]
set_property PACKAGE_PIN Y30 [get_ports data_out_1]
set_property PACKAGE_PIN H24 [get_ports load_1]
set_property PACKAGE_PIN G25 [get_ports rst_2]
set_property IOSTANDARD LVCMOS33 [get_ports rst_2]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sync_1]
set_property IOSTANDARD LVCMOS33 [get_ports data_out_1]
set_property IOSTANDARD LVCMOS33 [get_ports load_1]
set_property PACKAGE_PIN W22 [get_ports clk_dac_1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_dac_1]

set_property PACKAGE_PIN M19 [get_ports load_1]
set_property PACKAGE_PIN C19 [get_ports rst_2]
set_property PACKAGE_PIN AJ27 [get_ports clk_dac_1]
set_property PACKAGE_PIN AH30 [get_ports resetout_0]
set_property IOSTANDARD LVCMOS33 [get_ports resetout_0]

set_property PACKAGE_PIN E18 [get_ports resetdac_0]
set_property IOSTANDARD LVCMOS33 [get_ports resetdac_0]
set_property PACKAGE_PIN Y30 [get_ports data_out_1]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
